### PR TITLE
feat: add GvkParser in cluster cache

### PR DESCRIPTION
**Pull request by leoluz**
Relates to https://github.com/argoproj/argo-cd/issues/9071

Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
lgtm

**Comment by rishabh625** [comment]
Hey @leoluz : m still trying to understand the code, but i have a question, Was this change imported in argo-cd and tested ? (ValidatingWebhookConfiguration case): Bug causing wrong diff calculation inside nested lists in CRDs with managed fields ignore configs.

**Comment by rishabh625** [comment]
> Hey @leoluz : m still trying to understand the code, but i have a question, Was this change imported in argo-cd and tested ? (ValidatingWebhookConfiguration case): Bug causing wrong diff calculation inside nested lists in CRDs with managed fields ignore configs.
> 
> is there any fork we could know that this fixes above

looks like this has https://github.com/argoproj/argo-cd/pull/9170/files

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
