### PR TITLE
chore: bump kubernetes version to 0.30.x

### PR DESCRIPTION
**Pull request by sivchari**
I upgraded libs of Kubernetes.

### CODE REVIEW

**Review by joselitofilho — APPROVED** [review]
Well done. 👏

**Comment by crenshaw-dev** [comment]
Argo CD PR to test: https://github.com/argoproj/argo-cd/pull/19074

**Comment by joselitofilho** [comment]
Hi, @crenshaw-dev and @sivchari,

Thanks for your effort on this! Do you have any idea when this will be merged?

**Comment by crenshaw-dev** [comment]
@joselitofilho been sorting out issues on the Argo CD repo, hoping to merge it this week. https://github.com/argoproj/argo-cd/pull/19074

Either way, the change won't ship until Argo CD 2.13.

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
