### PR TITLE
feat: ignore endpointslice modified events, and add tests

### PR DESCRIPTION
**Pull request by fungiboletus**
This is related to [a comment stating that endpointslice should be ignored](https://github.com/argoproj/argo-cd/issues/9819#issuecomment-1171045786).

### CODE REVIEW

**Comment by sidewinder12s** [comment]
This would be useful, we have a lot of DaemonSets with services that are causing constant reconciliations due to constant cluster scaling.

**Comment by aaemula** [comment]
This change is awesome.
So we don't have to manually configure the `resource.exclusions`.

**Comment by aaemula** [comment]
@crenshaw-dev @alexmt @jessesuen PTAL

**Comment by diranged** [comment]
What needs to be done to get this over the hump? This has a serious load impact for us (https://github.com/argoproj/argo-cd/issues/15594#issuecomment-1936709854).

**Comment by fungiboletus** [comment]
Is there a scenario where you don't want EndpointSlice to be ignored? I saw the code was ready to add more ignored ressources so I just added it there.

I think it's fine to have default ignored ressources in `resource.exclusions` instead. I wouldn't mind if someone else feels like implementing it :D

**Comment by agaudreault** [comment]
@fungiboletus we do have them in the UI because they contain useful networking information to identify and debug some network problems. 

I'll create an issue for the 3.0 version to change the default settings :)

**Pull request closed without merging**
