### PR TITLE
Server-side apply

### PR DESCRIPTION
**Pull request by sathieu**
See https://github.com/argoproj/argo-cd/issues/2267

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM! Thank you @sathieu !


@leoluz can you please take a look as well? I think you know more about server side apply than me.

**Comment by leoluz** [comment]
When using server-side apply it is important to define the `fieldManager` to set the fields ownership to the proper actor. This is a [required field](https://github.com/kubernetes/apimachinery/blob/v0.22.2/pkg/apis/meta/v1/types.go#L571-L579) for `application/apply-patch` patches which is the [one used by SSA](https://github.com/kubernetes/kubectl/blob/v0.22.2/pkg/cmd/apply/apply.go#L443).

Im not sure if this the behaviour using the go client but in kubectl CLI if we don't provide the `fieldManager` it will automatically assign the manager as "kubectl" which is also undesirable.

I believe that we should expose a configuration to also set the manager when choosing server-side apply.

**Comment by jannfis** [comment]
> I believe that we should expose a configuration to also set the manager when choosing server-side apply.

I agree. Ideally, multiple consumers of gitops-engine (e.g. Argo CD instances) would be able to manage different parts of the same resource as well, as this is one of the main advantages of SSA. For Argo CD, we would need a unique identifier (maybe `argocd-<installation_namespace>` as the manager.

Also I wonder about what happens with the `applicationInstance` label, currently used to identify (exclusively) managed resources. Will Argo CD still set that label on a resource that is managed using Server-Side-Apply? How could we have multiple instances of Argo CD manage different parts of the same resource without them overwriting the label, or triggering a shared resource warning?

**Comment by varunsatokar** [comment]
When is this feature planned for release?

**Comment by leoluz** [comment]
@varunsatokar We are currently discussing the proposal and analysing the impact it will bring.
You are welcome to participate in the review if you have something to add:
https://github.com/argoproj/argo-cd/pull/8812

**Comment by leoluz** [comment]
FYI, just rebased this branch with `master` to address conflict.

**Pull request merged**
