### PR TITLE
feat: Extend sync-options annotation with Force=true (#525)

### PR DESCRIPTION
**Pull request by n9**
Implementation for #525, #414, https://github.com/argoproj/argo-cd/issues/5882

### CODE REVIEW

**Review by crenshaw-dev — COMMENTED** [review]
Looks good! Is there any existing unit testing for Replace which we could replicate for Force?

**Comment by n9** [comment]
@crenshaw-dev I have found: https://github.com/argoproj/gitops-engine/blob/c0ffe8428a23011ae9f6d0d3d01f9bf6200a4339/pkg/sync/sync_context_test.go#L755

But it seems to me that it just tests that the correct method is used.

How the "force" flag is tested?

**Comment by sidharthramesh** [comment]
Any updates on this?

**Comment by crenshaw-dev** [comment]
@n9 good question... I'm not sure how `resourceOps.GetLastResourceCommand(kube.GetResourceKey(tc.target)` works, but basically I'm looking for a way to verify that, when the Force=true option is specified, the kubectl action is actually performed with `--force` enabled.

**Comment by crenshaw-dev** [comment]
@n9 I believe the mock `ApplyResource` function could be modified to store that flag information. 

```go
func (r *MockResourceOps) ApplyResource(ctx context.Context, obj *unstructured.Unstructured, dryRunStrategy cmdutil.DryRunStrategy, force, validate, serverSideApply bool, manager string) (string, error) {
	r.SetLastValidate(validate)
	r.SetLastServerSideApply(serverSideApply)
	r.SetLastServerSideApplyManager(manager)
	r.SetLastResourceCommand(kube.GetResourceKey(obj), "apply")
	command, ok := r.Commands[obj.GetName()]
	if !ok {
		return "", nil
	}

	return command.Output, command.Err
}
```

**Comment by mcoklica1** [comment]
Hey @n9 @crenshaw-dev, any updates on testing this and proceeding forward? IIUC you want to see if force flag is visible via ArgoCD logs when sync happens (application-controller pod)?

**Comment by n9** [comment]
Unfortunately, I have to work on other things. Feel free to complete this PR.

**Comment by kkk777-7** [comment]
@crenshaw-dev Implemented unit test. Could you please take a look at [this PR](https://github.com/argoproj/gitops-engine/pull/560) when you have some time? Thank you.

**Comment by ChristianCiach** [comment]
This seems to be obsolete now that https://github.com/argoproj/gitops-engine/pull/560 has been merged, I think.

**Comment by ktzsolt** [comment]
Hi! 

First of all, thank you for the change! 

May I ask how (and when) will this be integrated into Argo CD? All I see for gitops-engine is that the latest release is 2 years old here https://pkg.go.dev/github.com/argoproj/gitops-engine?tab=versions
So I don't quite get the release management of this component.

**Pull request closed without merging**
