### PR TITLE
Update condition to select right pvc as child for statefulset

### PR DESCRIPTION
**Pull request by hanzala1234**
We have 2 pvc in namespace, one with name `emqx-data-sw-broker-0` for statefulset `sw-broker` and other one is `emqx-data-sw-broker-internal-0` for statefulset `sw-broker-internal` and both have same template name `emqx-data`. since `emqx-data-sw-broker-internal-0` contains prefix `emqx-data-sw-broker-`, it consider it as part of sw-broker statefulset which is not right. fixing condition to check if it contains number at the end of prefix

### CODE REVIEW

**Comment by bradenwright** [comment]
Any updates on this, I've experienced this issue as well and it would be nice to get it resolved.

**Comment by bradenwright** [comment]
any update on this issue?

**Comment by bradenwright** [comment]
any update on this?  It's a bug fix and its been open for over 4 months

**Comment by bradenwright** [comment]
i know @hanzala1234 did the work along with my company, I can try to take a look at that.  I should have time this week (I'm gonna be traveling tomorrow).

**Comment by pasha-codefresh** [comment]
Thank you @bradenwright

**Comment by bradenwright** [comment]
I've had a few fires pop up this week, so it will probably be a week or 2 til I have time to look into this.

**Comment by nerdeveloper** [comment]
Hello @pasha-codefresh We have added some test cases/examples into  the code, it is good to review now

**Comment by nerdeveloper** [comment]
Just another reminder that need to be checked please @pasha-codefresh

**Comment by pasha-codefresh** [comment]
@nerdeveloper will review it tomorrow, sorry, didnt notice your msg

**Comment by pasha-codefresh** [comment]
Looks great for me, just doing manual testing and will merge it

**Comment by pasha-codefresh** [comment]
Снимок экрана 2024-05-14 в 21 59 56

Issue is resolved, LGTM!

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@hanzala1234 , thank you for your contribution, feel free to open ArgoCD PR with gitops-engine version update, you can assign or tag me, i will review it

**Comment by hanzala1234** [comment]
thanks @pasha-codefresh for merging MR. I will work on it tomorrow

**Pull request merged**
