### PR TITLE
manage clusters via proxy

### PR DESCRIPTION
**Pull request by ls0f**
Signed-off-by: ls0f <lovedboy.tk@qq.com>

### CODE REVIEW

**Comment by jinnjwu** [comment]
@ls0f any change to merge PR, thanks

**Comment by jinnjwu** [comment]
@crenshaw-dev any change to merge PR, thanks

**Review by dje4om — APPROVED** [review]
I was able to observe the need of this change to be able to use a proxy with argocd.
This change is compliant according to the kubeconfig implementation which is now GA : https://kubernetes.io/docs/tasks/extend-kubernetes/socks5-proxy-access-api/

**Comment by jinnjwu** [comment]
any chance to merge pr？

**Comment by ls0f** [comment]
@alexmt @crenshaw-dev Is there any progress?

**Comment by manuelstein** [comment]
@jannfis, @alexmt, been waiting on this fix for 5 months.
[k8s client go has allowed a ProxyURL for 4 years already](https://github.com/kubernetes/client-go/blame/b46677097d03b964eab2d67ffbb022403996f4d4/tools/clientcmd/api/types.go#L95).
This PR simply passes the explicit cluster proxy [k8s.io/client-go clientcmdapi ProxyURL](https://github.com/kubernetes/client-go/blob/b46677097d03b964eab2d67ffbb022403996f4d4/tools/clientcmd/api/types.go#L95).
Is there anything we can do to get this merged?

**Comment by murillovaz** [comment]
Is there a reason this hasn't been merged yet? up

**Review by alexmt — APPROVED** [review]
Sorry, I guess the review took forever because non of the reviewers had experience using proxy.

I've worked recently on supporting proxy in the internal project and understand well enough meaning of this change. 

LGTM

**Comment by rochaporto** [comment]
For others looking at this, it seems to be available in 2.8.x releases of argocd:
https://github.com/argoproj/argo-cd/blob/v2.8.3/go.mod#L14C47-L14C52

**Pull request merged**
