### PR TITLE
chore: add CODEOWNERS

### PR DESCRIPTION
**Pull request by jmeridth**
Setting up CODEOWNERS file so people are automatically notified about new PRs. Pretty much matches [argoproj/argo-cd CODEOWNERS](https://github.com/argoproj/argo-cd/blob/master/CODEOWNERS) file.  Thank you @leoluz for that feedback (below).

### CODE REVIEW

**Comment by jmeridth** [comment]
Mentioning the folks in my assumed CODEOWNERS explicitly to ensure they want to be added.  I'm not trying to add to anyone's spam.

/cc @alexmt @crenshaw-dev @pasha-codefresh @ishitasequeira

Please advice who or what team/group could/should be in a CODEOWNERS file.

**Comment by jmeridth** [comment]
Also [@dthomson25 user's GitHub profile](https://github.com/dthomas25), listed as reviwer in OWNERS, is very barren (zero activity).  Any feedback?  Kind of wondering if bot/etc and we should remove from EMERITUS.md? (@dthomson25 apologies if you're legit 😄 )

**Comment by dthomson25** [comment]
> Also [@dthomson25 user's GitHub profile](https://github.com/dthomas25), listed as reviwer in OWNERS, is very barren (zero activity). Any feedback? Kind of wondering if bot/etc and we should remove from EMERITUS.md? (@dthomson25 apologies if you're legit 😄 )

All good, and the username in the PR is (https://github.com/dthomas25) instead of mine (https://github.com/dthomson25)! I use to work at Intuit and worked full time on the Argo project until I took another job that required me to step back. I helped review a lot of the initial docs for the gitops-engine.

**Comment by jmeridth** [comment]
> > Also [@dthomson25 user's GitHub profile](https://github.com/dthomas25), listed as reviwer in OWNERS, is very barren (zero activity). Any feedback? Kind of wondering if bot/etc and we should remove from EMERITUS.md? (@dthomson25 apologies if you're legit 😄 )
> 
> All good, and the username in the PR is (https://github.com/dthomas25) instead of mine (https://github.com/dthomson25)! I use to work at Intuit and worked full time on the Argo project until I took another job that required me to step back. I helped review a lot of the initial docs for the gitops-engine.

🤦 @dthomson25 thank you for clarifying.  My bad on getting the username incorrect. ❤️

**Comment by leoluz** [comment]
@jmeridth Basically `gitops-engine` repo should mirror the codeowners from the Argo CD repo.
Also, there is a long running task to merge this repo in Argo CD.

**Comment by jmeridth** [comment]
Discussed in 12/12/24 contributors meeting.  Getting CODEOWNERS to match argoproj/argo-cd CODEOWNERS is the path forward.

**Review by leoluz — APPROVED** [review]
Thank for working on this!
LGTM

**Pull request merged**
