### PR TITLE
chore: Bump Kubernetes clients to 1.29.2

### PR DESCRIPTION
**Pull request by sivchari**
This PR aims to updating Kubernetes version to 1.29.1

### CODE REVIEW

**Comment by sivchari** [comment]
Hi @leoluz. Could you review it, thanks.

**Comment by sivchari** [comment]
Hi, @pasha-codefresh . Could you review this PR ? Thanks.

**Comment by crenshaw-dev** [comment]
@sivchari are you still up for working on this? I have some time to help.

**Comment by crenshaw-dev** [comment]
@sivchari took a quick glance through, and it's looking good. Would you mind opening an Argo CD PR pointing at your gitops-engine fork so we can run those tests as well? Here's an example of how that looks: https://github.com/argoproj/argo-cd/pull/16967/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R296

**Comment by sivchari** [comment]
Hi @crenshaw-dev 
I'm sorry that I was late.
Thank you for watching my changes.

I've already opened the PR in ArgoCD. The following link is it and the only thing that I should do is to pass the CI.
So, if this PR is ready to be merged, I'd like to  merge this PR into gitops-engine.
https://github.com/argoproj/argo-cd/pull/17491

Thanks.

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @sivchari!

**Pull request merged**
