### PR TITLE
fix: specify correct versions

### PR DESCRIPTION
**Pull request by ash2k**
`v1.17.8` is not correct. The right dependency version is `v0.17.8`. I've also bumped a few dependencies.

### CODE REVIEW

**Comment by alexmt** [comment]
@ash2k , do we need this PR given that we are migrating to v1.18.6 in https://github.com/argoproj/gitops-engine/pull/102 ?

**Comment by ash2k** [comment]
@alexmt we do not, but I don't know how long it'll take to merge #102, so I opened this one too, which is a smaller change. If you want to merge #102 instead, that's great!

**Comment by alexmt** [comment]
I'm testing https://github.com/argoproj/gitops-engine/pull/102 right now.

Unfortunately, we don't have a lot of e2e tests for gitops-engine. We will work on adding e2e in the future. 

For now, I'm using Argo CD e2e tests (https://github.com/argoproj/argo-cd/pull/4046). I've found a few issues. I plan to send reverse PR to your fork https://github.com/ash2k/gitops-engine/pull/1 :) Still debugging one failed Argo CD e2e test

**Comment by alexmt** [comment]
Closing in favor of https://github.com/argoproj/gitops-engine/pull/102

**Comment by darshanime** [comment]
just for my understanding, since we are `replace`ing all the versions to [the correct `v0.17.8`](https://github.com/argoproj/gitops-engine/blob/f420bb91a1e6345b4f1fbce92e689cb6216c4828/go.mod#L28), is this required?

**Comment by ash2k** [comment]
@darshanime Good question! From https://github.com/golang/go/wiki/Modules#gomod:

> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. 

`gitops-engine` is a library, so when I use it, it's `replace` directives are ignored in my build.

**Pull request closed without merging**
